language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g web-component-tester
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - wct

notifications:
  email:
    - maslov.dmitrij@gmail.com
